### ISSUE TITLE
ImportError: No module named 'sandbox'

### ISSUE THREAD

**Issue by geeklfs** [gkahn13/gcg#1]
hi, I run the script 'python envs/rccar/square_cluttered_env.py', 
output 'ImportError: No module named 'sandbox'',
should I do some configuration?

**Comment by Taylor-Liu** [comment]
Clone the repository and add it to your PYTHONPATH

**Comment by AzinShamshirgaran** [comment]
Hi, I have the same problem, although I add the directory to PythonPath, still, I got this error. Can you explain how to add it to PythonPath? I added 
export PYTHONPATH="${PYTHONPATH}:/home/gcg/sandbox/gkahn/gcg"
to /.bashrc 
But it didn't work.

**Comment by gkahn13** [comment]
The path you are pasting in looks wrong: /home/gcg/sandbox/gkahn/gcg
(1) I'm assuming your username is not gcg (and hence shouldn't be /home/gcg)
(2) The path needs to point to the root of the repository, not sandbox/gkahn/gcg

**Comment by AzinShamshirgaran** [comment]
Thanks for your help. Still, I got the error:

"    from sandbox.gkahn.gcg.envs.rccar.cylinder_env import CylinderEnv
  File "/home/azin/sandbox/gkahn/gcg/envs/rccar/cylinder_env.py", line 5, in <module>
    from sandbox.gkahn.gcg.envs.rccar.car_env import CarEnv
  File "/home/azin/sandbox/gkahn/gcg/envs/rccar/car_env.py", line 4, in <module>
    from sandbox.gkahn.gcg.envs.rccar.panda3d_camera_sensor import Panda3dCameraSensor
  File "/home/azin/sandbox/gkahn/gcg/envs/rccar/panda3d_camera_sensor.py", line 3, in <module>
    from panda3d.core_module import WindowProperties, FrameBufferProperties
ImportError: No module named 'panda3d.core_module' "

Running 
_$ pip install --pre --extra-index-url https://archive.panda3d.org/ panda3d_
gives me
Requirement already satisfied: panda3d in /home/azin/anaconda2/envs/gcg/lib/python3.5/site-packages (1.10.0.dev1791+inputoverhaul.84)

**Comment by gkahn13** [comment]
Seems like you are having an issue with Panda3d. This could be due to your specific machine configuration. I suggest looking through the Panda3d tutorials and making sure you can run their basic examples.
