### ISSUE TITLE
If I want to see the result, which file should I run?

### ISSUE THREAD

**Issue by RFK97** [gkahn13/gcg#2]
I set all environment followed the 'Readme.md' step by step.
so I could saw simulation environment and the datafile being created.
($ python run_exp.py --exps ours
Creating your personal config from template...
Personal config created, but you should probably edit it before further experiments are run
Exiting.)

but I have no idea about how I can see the result on simulation environment or other way.
I know it's silly question, but now.. there's no other way except asking to solve this TT
please help me!

**Comment by gkahn13** [comment]
If you want to see the rollouts from the training process, change save_rollouts and save_rollouts_observations to True in the yaml file. Then, when you run the experiment, the rollouts will be saved to the experiment directory and you can load and visualize the rollouts (e.g., using matplotlib on the image observations).

If you want to see how good a specific policy is, take a look at eval_exp.py in sandbox/gkahn/gcg
