### ISSUE TITLE
To create new Environment 

### ISSUE THREAD

**Issue by ratheesh2107** [gkahn13/gcg#3]
Hi,

We are in a plan to create an environment which is somewhat similar to the one mentioned in the paper.
Can you suggest me the simulator tool you have used to create the environment.?

Regards,
Ratheesh

**Comment by gkahn13** [comment]
We used the Panda3d simulator and created the environments using Blender. This was sufficient to create simplistic environments, and Panda3d runs fairly quickly in these simple environments.

We did not find a good way to create complex environments. We have therefore switched to using more advanced simulators (e.g., CARLA, Gibson, AirSim) and writing our own environment classes that implement the step(...) and reset(...) functions and interface with these simulators.
